image: java:8

before_script:
  # - apt-get update
  - echo GitLab-CI BeforeScript Success1
  - chmod +x mvnw

compile:
  script:
    - echo Gitlab-CI Job1 ===> Compile
    - ./mvnw install
    artifacts:
      paths:
        - Module_WEB/target/Module_WEB-0.0.1-SNAPSHOT.jar